# Generated by Django 5.2 on 2025-04-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
