# Generated by Django 5.2 on 2025-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
